name: "Auto Assign"
on:
    pull_request:
        types: [opened, ready_for_review]

jobs:
    add-reviews:
        runs-on: self-hosted
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Run auto-assign-action
              uses: kentaro-m/auto-assign-action@v2.0.0
